### ISSUE TITLE
AttributeError: Can't pickle local object 'EfficientBenchmark.update_queue_runner.<locals>.new_cr'

### ISSUE THREAD

**Issue by c1a1o1** [minyoungg/selfconsistency#1]
win10, py3.5  error:

AttributeError: Can't pickle local object 'EfficientBenchmark.update_queue_runner.<locals>.new_cr'

**Comment by minyoungg** [comment]
We were unable to replicate this error. At first glance, this seems like an issue with windows-specific tensorflow.

**Comment by AndrewHLiu** [comment]
Looks like an issue with the multiprocessing data loader, can you give us a more detailed trace? I recognize the different names but it's hard to tell what's going on.

**Comment by c1a1o1** [comment]
Thank you very much!
